### ISSUE TITLE
exec: Failed to execute process: './pnut_ts' the file could not be run by the operating system (Linux x86-64)

### ISSUE THREAD

**Issue by meowmeowahr** [ironsheep/PNut-TS#1]
### and have you...

- [X] I updated to the latest spin2 version available
- [X] I have restarted VSCode and the problem still exists

### Version of Pnut TypeScript Implementation with the issue

v1.43.0 and v0.43.1

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Hardware, Operating System, Operating System version, VSCode version

Hardware: Intel x86-64 i9-14900HX
OS Ver: Arch Linux x86_64 kernel: 6.10.8-arch1-1
Shell: fish, version 3.7.1
VSCode Ver: N/A

### Description of problem

Linux 64-bit builds are compiled for ARM aarch64. 

`file` output of executable:
```
./pnut_ts: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=4786c866c75e9a87a389393cd98b619259af30dd, for GNU/Linux 3.7.0, stripped
```

**Comment by ironsheep** [comment]
Looking into this… answer later today (rechecking my packaging scripts)

- Stephen

**Comment by ironsheep** [comment]
OK, great find!  I Fixed bug in my packaging scripts. I've re-uploaded the .zip files built with the new scripts.
The filenames now also include a build version suffix  where v1.43.0 is seen as -014300.zip

Thank you for reporting this!

**Comment by meowmeowahr** [comment]
Thanks, it seems to be working now, though I am also having Ada's issue with the error messages after compilation 
(https://forums.parallax.com/discussion/comment/1561467/#Comment_1561467)
