### ISSUE TITLE
Add true -o option to specify a full filename.extension for pnut_ts output

### ISSUE THREAD

**Issue by dgately** [ironsheep/PNut-TS#4]
### Issue being Addressed

Currently, pnut_ts outputs a .bin filename for output of compiles. The current -o option allows changing the base filename but does not seem to allow changing the extension of the output file.

### Enhancement

I may be mistaken... But, aren't pnut (pnut_ts) .bin output files executable just as .binary executables from other P2 compiler programs (well, bytecode executables :-) ?

Other Parallax P2 loader apps/commands tend to use the .binary extension name. It would help if another option (or change to the -o option) allowed this change to be useful with other load programs. Isn't this the typical MO of other Unix/Linux programs that process an input file and output a resultant file with a -o option that allows file names with alternative extensions?

If I'm incorrect, please close this report!

THx!

**Comment by ironsheep** [comment]
Well, huh, I didn't know I did this. I wouldn't have thought I'd override the file type if you specified it. My bad.
I'll fix this later this week.

My goal is to allow both compilers to be used in the same project, so I'm not keen on changing the suffix, but I likely will make the output file the same with an option to override this behavior.

**Comment by ironsheep** [comment]
Fixed. Changes appear in v1.43.3 and later.
