### ISSUE TITLE
Allow empty VAR section

### ISSUE THREAD

**Issue by ironsheep** [ironsheep/PNut-TS#6]
### Issue being Addressed

JonnyMac's template has an empty VAR and other compilers don't complain

### Enhancement

Let's not generate an error for this condition.

**Comment by ChipGracey** [comment]
That is allowed in PNut. What is the problem? Is there a problem?

**Comment by ironsheep** [comment]
Yes, we never tested this condition, and our port caught it as an error.

Running final tests on fix now to ensure no regressions cause by my change.

**Comment by ironsheep** [comment]
Fixed. Changes appear in v1.43.3 and later.
